"""Utility functions for file, directory, and git operations."""

from .files import (
    fetch_image_as_data_url,
    fetch_url_bytes,
    fetch_url_text,
    get_current_working_directory,
    guess_attachment_extension,
    is_image_bytes,
    is_text_bytes,
    list_files,
    list_source_files_recursive,
    list_cwd_source_files_recursive,
    read_file,
    write_to_file,
)
from .git import (
    checkout,
    clone_github_repo,
    extract_github_user_attachment_links,
    extract_image_markdown,
    extract_issue_fields,
    fetch_issue_comments,
    format_issue,
    get_closed_issues,
    get_contributors,
    parse_github_issue_url,
    parse_github_repo_url,
    save_issue_details_to_json,
    save_issues_to_json,
    save_issues_to_text,
)
from .text import format_key_to_subheading

__all__ = [
    'checkout',
    'clone_github_repo',
    'extract_github_user_attachment_links',
    'extract_image_markdown',
    'fetch_image_as_data_url',
    'fetch_url_bytes',
    'fetch_url_text',
    'guess_attachment_extension',
    'is_image_bytes',
    'is_text_bytes',
    'extract_issue_fields',
    'fetch_issue_comments',
    'format_issue',
    'get_closed_issues',
    'get_contributors',
    'get_current_working_directory',
    'list_files',
    'list_source_files_recursive',
    'list_cwd_source_files_recursive',
    'read_file',
    'write_to_file',
    'parse_github_issue_url',
    'parse_github_repo_url',
    'save_issue_details_to_json',
    'save_issues_to_json',
    'save_issues_to_text',
    'format_key_to_subheading',
]
